### ISSUE TITLE
Problems when combining with doctrine-fixtures.

### ISSUE THREAD

**Issue by noggan** [zf-fr/zfr-oauth2-server#32]
I'm receiving the following error when running data-fixture:import with the --purge-with-truncate flag.

```[Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException]                        
  An exception occurred while executing 'TRUNCATE oauth_clients':                         
  SQLSTATE[42000]: Syntax error or access violation: 1701 Cannot truncate a table refere  
  nced in a foreign key constraint (`mie`.`oauth_refresh_tokens`, CONSTRAINT `FK_5AB6871  
  9EB6921` FOREIGN KEY (`client_id`) REFERENCES `mie`.`oauth_clients` (`id`))```

**Comment by macnibblet** [comment]
@Ocramius can this be resolved by using joinColumns ? And do we have any drawbacks in doing that ?

**Comment by bakura10** [comment]
I'd be happy to hear about this! I have no single idea unfortunately of how to solve that.

**Comment by macnibblet** [comment]
@bakura10 This can't be resolved due to MySQL's implementation of truncate. It does not listen to the cascade in the joinColumn. 

So the easiest way to solve this is by doing the following prior to running doctrine fixture truncate. 
```mysql
SET foreign_key_checks = 0;
```
