### ISSUE TITLE
use of AccessTokenStorage

### ISSUE THREAD

**Issue by basz** [zf-fr/zfr-oauth2-server#37]
Hi @bakura10 can you help me explain how to put the AccessTokenStorage out of the module and into the library module?

b.t.w. I got my branch sort of working in an expressive app.

What is it purpose? Seem to detect a Authorization Bearer token.

It reads from the request and seems to return an 'owner'

Shouldn't it become middleware by itself that set's an owner attribute on the request?

edit: The dependancy on Zend\Authentication\AuthenticationService is also obsolete?

**Comment by bakura10** [comment]
Hi,

You're right, in Expressive app (and middleware app), this works a bit differently and the AuthenticationService is obsolete.

What we are doing in our Expressive app is that we have created an "AuthenticationMiddleware". This middleware extract the token from the header, and try to retrieve the identity. Then you would set it as part of an attribute to the request:

```php
$request = $request->withAttribute(IdentityInterface::class, $loggedIdentity);
```

This would be the default middleware that ZfrOAuth2Server should provide (basically, delegate to the next middleware in all cases, and setting the logged identity).

If your app requires authentication on all endpoint, you could create an additional middleware (set after the AuthenticationMiddleware in your pipeline) that would check the presence of the identity:

```php
if (null === $request->getAttribute(IdentityInterface::class) {
    return new JsonResponse(['message' => 'Authentication required'], 401);
}
```

Hope it makes sense :)

**Comment by basz** [comment]
yes, lot's of sense. thx
