### ISSUE TITLE
Remove routing

### ISSUE THREAD

**Issue by bakura10** [zf-fr/zfr-oauth2-server#39]
For now, ZfrOAuth2 is based on Stratigility and provides its own routing:

https://github.com/zf-fr/zfr-oauth2-server/blob/master/src/Server/AuthorizationServerMiddleware.php#L50-L52

I think that we should remove that, and the app consumer is responsible to register its own routes. Then, each action (handleToken, handleRevocation...) should have its own action middleware that only does the given task.

**Comment by bakura10** [comment]
ping @basz

**Comment by basz** [comment]
agreed. lets merge #38 first

**Comment by basz** [comment]
done in #44
