### ISSUE TITLE
weird issue

### ISSUE THREAD

**Issue by basz** [zf-fr/zfr-oauth2-server#45]
Overriding an abstract method does not work in php7 but does in hhvm...

https://3v4l.org/3p3vL

I need to override our createNew method in the AuthorizationCodeToken Class...

What am i missing, idea?

**Comment by danizord** [comment]
Works if you make second argument optional: https://3v4l.org/2QrpC

PHP disallows changing API in derivations because that makes the derivation unusable as instance of parent class, and because there's no (real) method overloading in PHP:
```php
class Foo {
    public function doSomething($a) {
    }
}

function doSomethingWithFoo(Foo $foo) {
    // That should work because signature of Foo tells about only 1 argument
    $foo->doSomething('a');
}

class Bar extends Foo {
    // But here we change the API
    public function doSomething($a, $b) { // breaks polymorphism
    }
}

doSomethingWithFoo(new Bar()); // Would throw error missing second argument $b
```

**Comment by basz** [comment]
thanks, i was unaware of this... we work around this by changing method names.

abstract
[AbstractToken](https://github.com/basz/zfr-oauth2-server/blob/refactoring-domain/src/Server/Model/AbstractToken.php#L74)

concretes
[AccessToken](https://github.com/basz/zfr-oauth2-server/blob/refactoring-domain/src/Server/Model/AccessToken.php#L38)
[AuthorizationCode](https://github.com/basz/zfr-oauth2-server/blob/refactoring-domain/src/Server/Model/AuthorizationCode.php#L47)
[RefreshToken](https://github.com/basz/zfr-oauth2-server/blob/refactoring-domain/src/Server/Model/RefreshToken.php#L39)
