### ISSUE TITLE
Server Directory

### ISSUE THREAD

**Issue by basz** [zf-fr/zfr-oauth2-server#46]
Why do we have still have a 'Server' directory? I think every under 'src/Server' and 'tests/Server' can be easily moved to 'src/' and 'tests/'.

**Comment by basz** [comment]
or tests/src to be really consequent...

**Comment by bakura10** [comment]
The server sub naelspace is here just in case I also decide to create a "client" namespace some day.

However you're write, with PSR4 the top folder can be removed (if you modify the psr4 config in the composer.json obviously)
