### ISSUE TITLE
Respond with a 401/403 instead of 400

### ISSUE THREAD

**Issue by basz** [zf-fr/zfr-oauth2-server#53]
According to https://tools.ietf.org/html/rfc6749#section-5.2 an auth server may return a different response code then 400.

Specifically useful to instruct clients to invalidate sessions when a refresh token was expired / could not be refreshed. About to be supported by ember-simple-auth https://github.com/jpadilla/ember-simple-auth-token/pull/150/files#diff-b3b19e97b14851cfabb1e6558abfc6daR371

I would like to be able to configure in the oauth server what response code should be returned for these 'invalid_grant' exceptions

Dunno how yet, but it is something I would like,... Sessions would be invalidate once the user start to submit stuff, but then it is to late UX wise...
```
if (null === $refreshToken || $refreshToken->isExpired()) {
    $responseCode = $this->getConfig()['invalid_grant_response_code'] ?? 400;
    throw OAuth2Exception::invalidGrant('Refresh token is expired', $responseCode);
}
```

Q: Can we configure to always return a new refresh token when a new token is issued? (Is it allowed by specs, I think apigility could do this...) If we're starting to think about extra configuration options this might be the time...

**Comment by bakura10** [comment]
I'm okay for adding such an option. But the spec does not explicitly says that 401 or 403 should invalidate user. Can't Ember Simple Auth uses 400 as well for invalidating user?

For your second question, it is part of the spec: https://tools.ietf.org/html/rfc6749#section-5.1

Actually the password grant already returns the refresh token whenever the server has a refresh token grant configured (https://github.com/zf-fr/zfr-oauth2-server/blob/master/src/Grant/PasswordGrant.php#L129) but it seems it's not done the same way for the client credentials grant. I'm not 100% sure why I didn't do it... it may be worth re-reading the spec to make sure it's not explicitly forbidden by the spec but if that's not the case, I think you could add it for this grant as well.

**Comment by bakura10** [comment]
Also, your link to Ember-simple-Auth is actually to Ember-simple-auth-token (JWT implementation). ZfrOAuth2 does not support JWT token yet isn't it? :)

**Comment by basz** [comment]
About issuing new refresh tokens, that seems to be allowed.

> The authorization server MAY issue a new refresh token, in which case
>   the client MUST discard the old refresh token and replace it with the
>   new refresh token.  The authorization server MAY revoke the old
>   refresh token after issuing a new refresh token to the client.  If a
>   new refresh token is issued, the refresh token scope MUST be
>   identical to that of the refresh token included by the client in the
>   request.

Which would suggest THREE configurable options to me;

- issue_refresh_token: Might not want refresh tokens at all?
- refresh_refresh_token
- revoke_old_refresh_token: suggesting to be kept at TRUE. (Although I vaguely remember two instances of the same client (2 windows) might have problems with that).

I didn't realised that that ember repo wasn't about ember-simple-auth build-in oauth2 support. It provides an alternative (that might be dropped in future versions) and JWT tokens. Something to keep an eye on... zfr-oauth2-server doesn't support JWT Tokens yet but I'm aware you would like that... Anyway I've asked them why they choose for 401/403 only...

**Comment by bakura10** [comment]
I don't think we need an "issue_refresh_token" option: if you want, just add the RefreshTokenGrant, otherwise just don't add it.

What does the "refresh_refresh_token" does? Sounds a strange name.

**Comment by basz** [comment]
refresh_refresh_token should turn on/off the fact if one gets a new refresh token when a token is refreshed with a refresh_token. currently I get the same refresh token again and again until it expires. naming is not thought through...

no 'issue_refresh_token'... clear

**Comment by bakura10** [comment]
for the refresh_refresh_token, isn't it already handled by the rotateToken option: https://github.com/zf-fr/zfr-oauth2-server/blob/master/src/Grant/RefreshTokenGrant.php#L128 ?

**Comment by basz** [comment]
uhm, oops yes... never saw that one...

**Comment by basz** [comment]
rotateRefreshTokens is not configurable though: [factory](https://github.com/zf-fr/zfr-oauth2-server/blob/master/src/Container/RefreshTokenGrantFactory.php), [ServerOptions](https://github.com/zf-fr/zfr-oauth2-server/blob/master/src/Options/ServerOptions.php) So I think we could polish a bit on that part of the lib

**Comment by basz** [comment]
closing the main issue - as after rereading the specs a 400 return code should be returned for errors (unless specified otherwise) which it isn't for 'invalid_client' errors.
