### ISSUE TITLE
Improve configuration

### ISSUE THREAD

**Issue by basz** [zf-fr/zfr-oauth2-server#54]
Configuration requires a little polishing as not all parts are configurable. see discussed at #53

Besides identifying what options are present but not configurable, we additionally might think about setting options per grant type and there combinations? I mean someone might want refresh_token rotated for the PasswordGrant but not for the ClientCredentialsGrant. Perhaps someone wants no refresh tokens at all for on PasswordGrants but for ClientCredentialsGrant he does. Not registering RefreshTokenGrant is not an option then. I do want to express that I probably won't be using such fine-grained control so for me it would be ok to just leave it. Would avoiding adding additional complexity.

- [x] rotateRefreshTokens can not be configured currently
- [x] revokeRotatedRefreshTokens, should be added
- [ ] #53 configure responseCode to be other then 400 for `invalid_grant` responses. (and others?)

**Comment by bakura10** [comment]
I'm not really sure that using different grant types is such a common use case. I don't feel the extra complexity in having per grant config is worthwhile.

Envoyé de mon iPhone

**Comment by basz** [comment]
can be closed
