### ISSUE TITLE
Q: container names be interface

### ISSUE THREAD

**Issue by basz** [zf-fr/zfr-oauth2-server#64]
Should container names reference Interface where ever possible?

ResourceServer vs ResourceServerInterface
AuthorizationServer vs AuthorizationServerInterface

example:

https://github.com/zf-fr/zfr-oauth2-server/blob/master/src/Container/ResourceServerMiddlewareFactory.php#L38
https://github.com/zf-fr/zfr-oauth2-server/blob/a4b9715a17f9bd1f0d2f3254881162ff75accf68/src/Container/AuthorizationRequestMiddlewareFactory.php#L38
https://github.com/zf-fr/zfr-oauth2-server/blob/a4b9715a17f9bd1f0d2f3254881162ff75accf68/src/Container/TokenRequestMiddlewareFactory.php#L38

**Comment by prolic** [comment]
:+1: for referencing interfaces
