### ISSUE TITLE
PHP CS issues

### ISSUE THREAD

**Issue by prolic** [zf-fr/zfr-oauth2-server#80]
see https://travis-ci.org/zf-fr/zfr-oauth2-server/jobs/204914919

**Comment by ojhaujjwal** [comment]
Hello guys. this may not be a good thread to ask this question.
But, I have been watching some activity in this repo. There have been a lot of changes. Is there any target or roadmap for the next release?

**Comment by basz** [comment]
Hi,

I think were up for a beta version soon. We still need more testing and some documentation though.

Bas
